# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dries/Projects/Basys3/VGA_text/VGA_text.srcs/sources_1/ip/FiFo/FiFo.xci
# IP: The module: 'FiFo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dries/Projects/Basys3/VGA_text/VGA_text.srcs/sources_1/ip/FiFo/FiFo/FiFo.xdc
# XDC: The top module name and the constraint reference have the same name: 'FiFo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dries/Projects/Basys3/VGA_text/VGA_text.srcs/sources_1/ip/FiFo/FiFo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FiFo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dries/Projects/Basys3/VGA_text/VGA_text.srcs/sources_1/ip/FiFo/FiFo.xci
# IP: The module: 'FiFo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dries/Projects/Basys3/VGA_text/VGA_text.srcs/sources_1/ip/FiFo/FiFo/FiFo.xdc
# XDC: The top module name and the constraint reference have the same name: 'FiFo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dries/Projects/Basys3/VGA_text/VGA_text.srcs/sources_1/ip/FiFo/FiFo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FiFo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
