# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dries/Projects/Basys3/FPGA-Z/FPGA-Z.srcs/sources_1/ip/Stack/Stack.xci
# IP: The module: 'Stack' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dries/Projects/Basys3/FPGA-Z/FPGA-Z.srcs/sources_1/ip/Stack/Stack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Stack'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dries/Projects/Basys3/FPGA-Z/FPGA-Z.srcs/sources_1/ip/Stack/Stack.xci
# IP: The module: 'Stack' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dries/Projects/Basys3/FPGA-Z/FPGA-Z.srcs/sources_1/ip/Stack/Stack_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Stack'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
